variables:
  homepage: https://github.com/sjultra/speedtest
  repository: https://github.com/sjultra/speedtest
  description: Exports Speedtest results to the Prometheus format

includes:
  - from_url:
      url: https://raw.githubusercontent.com/sjultra/speedtest/build.yml
  - from_url:
      url: https://raw.githubusercontent.com/sjultra/speedtest/release.yml
  - from_url:
      url: https://raw.githubusercontent.com/sjultra/speedtest/docker.yml

before:
  hooks:
    - go mod tidy

nfpms:
  - vendor: Becker Software LTDA
    homepage: '{{ .homepage }}'
    maintainer: SJUltra Team <eng@sjultra.com>
    description: '{{ .description }}'
    formats:
      - apk
      - deb
      - rpm
    overrides:
      deb:
        dependencies:
          - speedtest
      rpm:
        dependencies:
          - speedtest
brews:
- tap:
    owner: sjultra
    name: homebrew-tap
  folder: Formula
  description: '{{ .description }}'
  homepage: '{{ .homepage }}'
  dependencies:
    - name: speedtest

furies:
- account: sjultra