---
version: "1.0"
services:
  speedtest:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    # environment:
    #   - INFLUXDB_HOST=influxdb
    #   - INFLUXDB_DB=speedtest
    #   - INFLUXDB_USERNAME=admin
    #   - INFLUXDB_PASSWORD=password
    #   - SPEEDTEST_HOST=local
    #   - SPEEDTEST_INTERVAL=3600
    restart: unless-stopped
    depends_on:
      - "influxdb"
      - "grafana"

  influxdb:
    image: sjultra/influxdb-legacy:latest
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - DB_NAME=speedtest
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    ports:
      - 8086:8086
    restart: always
      
  grafana:
    image: grafana/grafana:10.1.2
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./helm/service/files/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./helm/service/files/grafana/datasources:/etc/grafana/provisioning/datasources
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - "influxdb"
