apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pewpew
  labels:
    app: pewpew
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pewpew
  template:
    metadata:
      labels:
        app: pewpew
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP