apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "<chart-name>.fullname" . }}-grafana-provisioning-datasources
data:
  {{- range $path, $bytes := .Files.Glob "files/grafana/provisioning/datasources/*" }}
  {{ $path | replace "files/grafana/provisioning/datasources/" "" }}: |-
    {{ $.Files.Get $path | nindent 4 }}
  {{- end }}
