apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      initContainers:
        - name: influxdb-wait
          image: busybox:1.34.0
          command: ["sh", "-c", "until nslookup influxdb; do sleep 2; done"]
      containers:
        - name: grafana
          image: {{ .Values.grafana.image }}
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-provisioning-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-provisioning-datasources
              mountPath: /etc/grafana/provisioning/datasources
          env:
            - name: GF_SERVER_ROOT_URL
              value: "{{ .Values.grafana.ROOTURL }}"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "{{ .Values.grafana.adminPassword }}"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
      volumes:
        - name: grafana-provisioning-dashboards
          configMap:
            name: {{ include "<chart-name>.fullname" . }}-grafana-provisioning-dashboards
        - name: grafana-provisioning-datasources
          configMap:
            name: {{ include "<chart-name>.fullname" . }}-grafana-provisioning-datasources
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: {{ .Values.grafana.port }}
      targetPort: 3000

