apiVersion: v2
name: speedtest-cron
description: A network diagnositics cron job based on the official Speed Test CLI
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - email: contact@sjultra.com
    name: devopssju
